name: ruspy
channels:
  - opensourceeconomics
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - sphinx
  - pandas
  - statsmodels
  - pytest
  - pytest-xdist
  - pytest-cov
  - scipy
  - matplotlib
  - numpydoc
  - jupyter
  - numba
  - mpmath
  - pip
  - estimagic>=0.0.27
  - pip:
      - flake8
      - black
      - pre-commit
      - jupyter_contrib_nbextensions
      - sphinx_rtd_theme
